env:
  browser: true
  es6: true
  node: true

extends:
  - 'eslint:recommended'

# parser: '@babel/eslint-parser'

parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    classes: true
    experimentalObjectRestSpread: true
    jsx: true
